name: hakyll-convert
version: 0.3.0.4
synopsis: Convert from other blog engines to Hakyll.
description: WordPress and Blogger only let one export posts in
             a limited number of formats, none of which are supported
             by Hakyll. @hakyll-convert@ is created to bridge this gap,
             providing a way to turn other platform's datadumps into
             a set of files Hakyll understands.
github: Minoru/hakyll-convert
license: BSD3
license-file: LICENSE
author: Eric Kow <eric.kow@gmail.com>, Alexander Batischev <eual.jp@gmail.com>
maintainer: Alexander Batischev <eual.jp@gmail.com>
extra-source-files:
  - CHANGELOG.md
  - test/golden/data/blogger-000/input.xml
  - test/golden/data/blogger-000/*.golden
  - test/golden/data/blogger-001/input.xml
  - test/golden/data/blogger-001/*.golden
  - test/golden/data/blogger-002/input.xml
  - test/golden/data/blogger-002/*.golden
  - test/golden/data/io-000/*.golden
  - test/golden/data/wordpress-000/input.xml
  - test/golden/data/wordpress-000/*.golden
  - test/golden/data/wordpress-001/input.xml
  - test/golden/data/wordpress-001/*.golden
category: Tools

# These are part of the library's API, so might as well require them for all
# the targets.
dependencies:
  - base >= 4.13 && < 5
  - text >= 1.2 && < 1.3
  - xml-types >= 0.3 && < 0.4

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - Hakyll.Convert.Blogger
    - Hakyll.Convert.Common
    - Hakyll.Convert.IO
    - Hakyll.Convert.OutputFormat
    - Hakyll.Convert.Wordpress
  dependencies:
    - bytestring >= 0.10 && < 0.12
    - containers >= 0.6 && < 0.7
    - data-default >= 0.7 && < 0.8
    - directory >= 1.3 && < 1.4
    - feed >= 1.3 && < 1.4
    - filepath >= 1.4 && < 1.5
    - time >= 1.9 && < 1.10
    - xml-conduit >= 1.9 && < 1.10

executable:
  main: hakyll-convert.hs
  source-dirs: app
  dependencies:
    - hakyll-convert

    - cmdargs >= 0.10 && < 0.11
    - filepath >= 1.4 && < 1.5

tests:
  golden:
    main: Main.hs
    source-dirs: test/golden
    # We need an orphan Show DistilledPost instance
    ghc-options: -Wno-orphans
    dependencies:
      - hakyll-convert

      - bytestring >= 0.10 && < 0.12
      - data-default >= 0.7 && < 0.8
      - feed >= 1.3 && < 1.4
      - filepath >= 1.4 && < 1.5
      - tasty >= 1.2 && < 1.5
      - tasty-golden >= 2.3 && < 2.4
      - temporary >= 1.3 && < 1.4
      - time >= 1.9 && < 1.10

  spec:
    main: Main.hs
    source-dirs: test/spec
    # We need an orphan Show DistilledPost instance
    ghc-options: -Wno-orphans
    dependencies:
      - hakyll-convert

      - data-default >= 0.7 && < 0.8
      - directory >= 1.3 && < 1.4
      - feed >= 1.3 && < 1.4
      - filepath >= 1.4 && < 1.5
      - tasty >= 1.2 && < 1.5
      - tasty-expected-failure >= 0.12.2 && < 0.13
      - tasty-hunit >= 0.10 && < 0.11
      - tasty-quickcheck >= 0.10 && < 0.11
      - temporary >= 1.3 && < 1.4
      - time >= 1.9 && < 1.10
