name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    name: Stack on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ matrix.os }}-${{ hashFiles('package.yaml', 'stack.yaml', 'stack.yaml.lock') }}-r2
          path:
            ~/.stack

      - name: Build
        run: stack test --haddock --ghc-options '-Werror'
