name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        plan:
          - os: ubuntu-20.04
            extra_stack_args: ""
          - os: macos-10.15
            extra_stack_args: ""
          - os: windows-2019
            # Skip golden tests since they depend on Unix line endings.
            extra_stack_args: "--skip golden"

    name: Stack on ${{ matrix.plan.os }}
    runs-on: ${{ matrix.plan.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ matrix.plan.os }}-${{ hashFiles('package.yaml', 'stack.yaml', 'stack.yaml.lock') }}-r3
          path:
            ~/.stack

      - name: Build
        run: stack test --haddock --ghc-options '-Werror' ${{ matrix.plan.extra_stack_args }}
