name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build with Stack
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('package.yaml', 'stack.yaml', 'stack.yaml.lock') }}
          path: |
            ~/.stack

      - name: Build
        run: stack test --haddock --ghc-options '-Werror'
