name: HLint

on: [push, pull_request]

jobs:
  build:
    name: Run HLint
    runs-on: ubuntu-22.04

    env:
      hlint_version: "3.6.1"

    steps:
      - name: Cache HLint installed from source
        id: cache
        uses: actions/cache@v4
        with:
          key: hlint-${{ env.hlint_version }}
          path: |
            ~/.stack
            ~/.local/bin

      - name: Install HLint
        if: steps.cache.outputs.cache-hit != 'true'
        run: stack --resolver lts-22.23 install hlint-${{ env.hlint_version }}

      - uses: actions/checkout@v4

      - name: Run HLint
        run: ~/.local/bin/hlint .
