name: HLint

on: [push, pull_request]

jobs:
  build:
    name: Run HLint
    runs-on: ubuntu-20.04

    env:
      hlint_version: 3.3.6

    steps:
      - name: Cache HLint installed from source
        id: cache
        uses: actions/cache@v2
        with:
          key: hlint-${{ env.hlint_version }}
          path: |
            ~/.stack
            ~/.local/bin

      - name: Install HLint
        if: steps.cache.outputs.cache-hit != 'true'
        run: stack install hlint-${{ env.hlint_version }}

      - uses: actions/checkout@v2

      - name: Run HLint
        run: ~/.local/bin/hlint .
